### ISSUE TITLE
[FR] Support auto link functionality

### ISSUE THREAD

**Issue by shejialuo** [blueset/efb-telegram-master#125]
**Is your feature request related to a problem? Please describe.**  
Now, if we want the messages isolated, we need to use the link functionality. But sometimes it is tedious to create a group in telegram and send the `/link <id>` to the bot to link the corresponding group.

**Describe the solution you'd like**  
I think maybe we could add reply to the message which we want to link to the group. Just like the functionality where we could withdraw our messages in the slave channel. We could reply a command such as `/autolink` or `/addgroup`. The master channel could automatically create a group (I don't know whether bot could create a group.) for us to do `/link`. Thus, we could make a better experience for users.

**Describe alternatives you've considered**  
None

**Additional context**  
None

**Comment by blueset** [comment]
You can already reply `/link` to an existing message from a slave channel for quick selection. 

However, unfortunately, Telegram Bot API does not allow a bot to creat groups, so users would still have to creat groups themselves.
