### ISSUE TITLE
connect to other telegram bot support in one conversation?

### ISSUE THREAD

**Issue by yongman** [blueset/efb-telegram-master#22]
Can the `etm` support add other telegram bot in one conversation and use it in slave channel, such as wechat?

**Comment by blueset** [comment]
I'm not quite sure what you were asking for, but as far as I can interpret, I assume that you are trying to get ETM to forward messages from other bots. 

If that is the case, unfortunately that is not possible. Telegram does not allow communications between bots to avoid potential dead loop to occur. There is nothing we can do on this by far. 

Please reopen the issue and explain in detail if you were asking for something else.

**Comment by yongman** [comment]
Sorry for my unclear description, but your interpret is right.

Thanks for your reply.
