### ISSUE TITLE
Something wrong with the linked chat

### ISSUE THREAD

**Issue by Powerfan** [blueset/efb-telegram-master#36]
After linking a chat to a group successfully, it doesn't  work. When the chat sends a new message, it can't forward to the group and shows the following error:

> BadRequest()
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/site-packages/efb_telegram_master/slave_message.py", line 138, in send_message
>     tg_msg = self.slave_message_file(msg, tg_dest, msg_template, old_msg_id, target_msg_id, reply_markup)
>   File "/usr/local/lib/python3.6/site-packages/efb_telegram_master/slave_message.py", line 374, in slave_message_file
>     reply_markup=reply_markup)
>   File "/usr/local/lib/python3.6/site-packages/efb_telegram_master/bot_manager.py", line 201, in caption_affix
>     return fn(self, *args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/efb_telegram_master/bot_manager.py", line 312, in send_document
>     return self.updater.bot.send_document(*args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/telegram/bot.py", line 65, in decorator
>     result = func(self, *args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/telegram/bot.py", line 90, in decorator
>     result = self._request.post(url, data, timeout=kwargs.get('timeout'))
>   File "/usr/local/lib/python3.6/site-packages/telegram/utils/request.py", line 305, in post
>     result = self._request_wrapper('POST', url, fields=data, **urlopen_kwargs)
>   File "/usr/local/lib/python3.6/site-packages/telegram/utils/request.py", line 223, in _request_wrapper
>     raise BadRequest(message)
> telegram.error.BadRequest: Wrong url host

**Operating system: | Centos 7 x86_64 bbr**

**Comment by blueset** [comment]
Since this error is a network based error, I would like to recommend you to check your connection to Telegram API.
