### ISSUE TITLE
'PhotoSize' object has no attribute 'msg_type'

### ISSUE THREAD

**Issue by Sistercon** [blueset/efb-telegram-master#41]
File: <tempfile._TemporaryFileWrapper object at 0x7fcf9c5b0390> (None @ /tmp/tmpfcyd0592), image/jpeg; Vendor: {}>
AttributeError("'PhotoSize' object has no attribute 'msg_type'",)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/efb_telegram_master/slave_message.py", line 202, in send_message
    mime=attachment.msg_type)
AttributeError: 'PhotoSize' object has no attribute 'msg_type'

**Comment by blueset** [comment]
Fixed in b79a5a6, will be released in the next version.
