### ISSUE TITLE
pkg_resources.ContextualVersionConflict: (imageio 2.4.1 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('imageio<3.0,>=2.5'), {'moviepy'})

### ISSUE THREAD

**Issue by kevinzhang1234** [blueset/efb-telegram-master#52]
![image](https://user-images.githubusercontent.com/46987925/55537626-381b5a80-56ef-11e9-873d-8bbe86bd0cfb.png)

ubuntu16.04，python 3.6.7
ehforwarderbot执行错误，请问怎么解决@blueset

**Comment by blueset** [comment]
Refer to issue [Zulko/moviepy#911](https://github.com/Zulko/moviepy/issues/911).

Try upgrade your `setuptools` using:

```bash
python3 -m pip install --upgrade setuptools
```
