### ISSUE TITLE
Some pictures sent as files with no extensions

### ISSUE THREAD

**Issue by AkazaDorian** [blueset/efb-telegram-master#71]
![](https://i.imgur.com/lLQ4dKw.png)

Happens with both WeChat and QQ slaves so I suppose it to be a bug on this side.  

By appending the extension to the file name (e.g. ".jpg"), the file can be opened and viewed, so it's only a problem of naming.

**Comment by blueset** [comment]
Fixed by wolfsilver in #72, will be released in next version.

**Comment by blueset** [comment]
Released in 2.0.0b27.
