### ISSUE TITLE
[BUG] efb-wizard connection error when asking for token

### ISSUE THREAD

**Issue by AndyChen2005121** [blueset/efb-telegram-master#91]
**Describe the bug**  
**"Connection refused" when asking to input token.**

**To Reproduce**  
**Go through efb-wizard.**

**Expected behavior**  
~~A clear and concise description of what you expected to happen.~~

**Screenshots**  
~~If applicable, add screenshots to help explain your problem.~~

**Version information (please complete the following information):**  
- Detailed Python, EFB and module versions: (you can obtain this by running `ehforwarderbot --version`)

EH Forwarder Bot
Version: 2.0.0b25
Python Version:
3.7.5 (default, Nov  1 2019, 02:16:32)
[Clang 11.0.0 (clang-1100.0.33.8)]

Master:
    Telegram Master (blueset.telegram) 2.0.0b38

Slave:
    WeChat Slave (blueset.wechat) 2.0.0a37 

Middleware:
    GnuPG Middleware (blueset.gpg) 1.0.1.post1 

**Additional context**  
 ```
urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org',
port=443): Max retries exceeded with url:
/bot1045277308:AAFE86tiOxMoisNqfRRtTiQdyYDr83Mz3Mg/getMe (Caused by Ne
wConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.Veri
fiedHTTPSConnection object at 0x10e8bc390>: Failed to establish a new
connection: [Errno 61] Connection refused'))
```

**Comment by blueset** [comment]
Please make sure that you can connect to the Telegram Bot API (`https://api.telegram.org`) on your server.

**Comment by AndyChen2005121** [comment]
@blueset I COULD connect to the bot API. (ping works, at least, for the non-https domain.) However, under a working proxy the error still occurs.
```
$ ping api.telegram.org
PING api.telegram.org (149.154.167.220): 56 data bytes
64 bytes from 149.154.167.220: icmp_seq=0 ttl=52 time=379.456 ms
64 bytes from 149.154.167.220: icmp_seq=1 ttl=52 time=290.878 ms
64 bytes from 149.154.167.220: icmp_seq=2 ttl=52 time=290.661 ms
^C
--- api.telegram.org ping statistics ---
3 packets transmitted, 3 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 290.661/320.332/379.456/41.807 ms

$ ping https://api.telegram.org
PING https://api.telegram.org (75.126.150.210): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
^C
--- https://api.telegram.org ping statistics ---
3 packets transmitted, 0 packets received, 100.0% packet loss
```

**Comment by blueset** [comment]
First of all, `ping` only ensures that you can receive ICMP responses from the server specified, it does not check any HTTP or rather TCP connections.

Your first `ping` seems has resolved the server to the correct IP, so there is no problem about DNS by far.

Please check if you can query Telegram Bot API by running the following command:

```bash
curl -i https://api.telegram.org/bot1045277308:AAFE86tiOxMoisNqfRRtTiQdyYDr83Mz3Mg/getMe
```

If that has returned the proper response, please run `efb-wizard`, as well as `ehforwarderbot` after you finish the configuration, in the *exact same settings*, that includes same network connection, same environment variables, behind same proxy (if any) and so on.

I have tested just now on my local machine, that ETM setup wizard is doing its job properly on detecting connectivity to Telegram server.
